// Report 공개 API (STEP 09-1). Project State → ReportInput → ReportModel → (Renderer / Export, STEP 09-2)
export { buildReportInput, aiAnalysisFromWorkflow } from './input.ts';
export type { ReportInput, AiAnalysisInput, ReportSnapshotInfo, BuildReportInputOptions } from './input.ts';
export { buildReport } from './buildReport.ts';
export type { ReportBuildResult, BuildReportOptions } from './buildReport.ts';
export { validateReportInput } from './validation/validate.ts';
export type { ReportValidation, ReportIssue } from './validation/validate.ts';
export { serializeReport, parseReport } from './export/snapshot.ts';
export type { ReportModel } from './model.ts';
export { REPORT_SCHEMA_VERSION } from './types.ts';
export type { Cell, DataKind, CellState, SourceRef, Narrative, NarrativeItem } from './types.ts';
export { REPORT_UNIT_POLICY } from './units.ts';
export { buildReportDocument, validateTemplate, valuationStandardV1, getTemplate, markersOf, markerText } from './templates/index.ts';
export type { ReportDocument, ReportTemplate, SectionTemplate, ResolvedSection, SectionId, SourceEntry } from './templates/index.ts';
export { buildPresentation } from './presentation/buildPresentation.ts';
export type { Presentation, TableModel, ChartModel, KpiModel, PCell } from './presentation/types.ts';
export { buildNarrative } from './narrative/buildNarrative.ts';
export type { ReportNarrative, NarrativeRejection, RejectionReason, NarrativeSectionId } from './narrative/buildNarrative.ts';
export { checkCitations } from './qa/citations.ts';
export type { CitationReport } from './qa/citations.ts';
export { buildRenderModel, reportFilename } from './render/buildRenderModel.ts';
export { renderReportHtml, REPORT_CSS, markerHtml } from './render/html.ts';
export { chartToSvg } from './render/svg.ts';
export { buildBundle, parseBundle, renderHashOf } from './export/bundle.ts';
export type { RenderModel, RenderBlock } from './render/types.ts';
export type { ReportBundle } from './export/bundle.ts';
export { generateReport, reopenReport, withHiddenOptionalSections } from './pipeline.ts';
export type { GenerateResult, GenerateOptions } from './pipeline.ts';
export { runReportQa, keyTexts } from './qa/validate.ts';
export type { QaReport, QaFinding, QaCategory } from './qa/validate.ts';
export type { GenerateOk, ViewableReport } from './pipeline.ts';
