// AI Valuation Analyst 공개 진입점 (STEP 08-1: 아키텍처). LLM 호출은 없다.
// 이 폴더는 valuation 내부 파일을 import 하지 않는다: 공개 API(valuation/index.ts)와 engine / store 의 모델만 사용한다.
export { buildAiContext } from './context.ts';
export type { AiValuationContext, AiContextOptions, CompanySupport, AiCompany } from './context.ts';
export { CAPABILITIES, classifyQuestion } from './capabilities.ts';
export type { Capability, CapabilityId, AnswerMode, QuestionClassification } from './capabilities.ts';
export { TOOL_CATALOG, TOOL_NAMES, FRONTEND_TOOL_NAMES, TOOL_RESULT_ENVELOPE, getToolDefinition } from './tools/definitions.ts';
export type { AiToolDefinition, ToolName, ToolExecution, JsonSchema } from './tools/definitions.ts';
export { executeTool, validateToolInput } from './tools/registry.ts';
export { getCompanyOverview, getHistoricalAnalysis } from './tools/historical.ts';
export { getHistoricalQuality, getMappingTrace } from './tools/quality.ts';
export { getForecastAssumptions, getValuationResult, getSensitivityAnalysis, getScenarioAnalysis, getRelativeValuation } from './tools/modelTools.ts';
export { missing } from './tools/result.ts';
export type { Missing, ToolResult, ToolWarning, SourceInfo } from './tools/result.ts';
export { auditAnswer, enforceGrounding, toAnswerSource } from './answer.ts';
export type { GroundingOutcome } from './answer.ts';
export type { AiAnalystAnswer, AnswerEvidence, AnswerSource, AnswerViolation } from './answer.ts';
export { SYSTEM_POLICY, AI_POLICY_RULES, UNSUPPORTED_DISCLOSURE, buildSystemInstruction } from './policy.ts';
export { createAuditEvent } from './audit.ts';
export type { AiAuditEvent, AiQueryAuditEvent, AiFinalStatus } from './audit.ts';
export { BackendAiClient, AiClientError } from './client.ts';
export type { AiGatewayClient, AiQueryRequest, AiToolResultRequest, GatewayResponse, ToolCallResponse, FinalResponse, ToolLimitResponse } from './client.ts';
export { runAiQuery, MAX_CLIENT_ROUNDS } from './query.ts';
export type { AiQueryOutcome, RunAiQueryOptions } from './query.ts';
export { buildMinimalContext } from './minimalContext.ts';
export { WORKFLOWS, WORKFLOW_BY_TYPE } from './agent/workflows.ts';
export { planWorkflow, classifyWorkflow, AGENT_MAX_TOOL_CALLS } from './agent/planner.ts';
export { observe } from './agent/observation.ts';
export { runWorkflow, resolveCheckpoint, snapshotId, MAX_WORKFLOW_STEPS } from './agent/run.ts';
export type { RunWorkflowOptions } from './agent/run.ts';
export type { WorkflowType, WorkflowPlan, WorkflowStep, WorkflowState, WorkflowStatus, WorkflowAnswer, WorkflowAuditEvent, WorkflowOutcome, HumanCheckpoint, Observation, EvidenceClaim, CheckpointKind, StepStatus } from './agent/types.ts';
export { extractEvidence, groundAnalysis, normalizeClaims } from './grounding/verify.ts';
export { groundWithRepair } from './grounding/repair.ts';
export { parseNumbers, matchesValue } from './grounding/numbers.ts';
export { termsIn, koreanAliases, TERMS } from './grounding/terms.ts';
export { evidenceConfidence, claimConfidence, sourcePriority } from './grounding/confidence.ts';
export { detectContradictions } from './grounding/contradiction.ts';
export { validateProposal } from './grounding/wacc.ts';
export type { Evidence, GroundedClaim, RawClaim, ClaimType, Confidence, GroundingReport, GroundingAuditEvent, NumberCheck, Contradiction } from './grounding/types.ts';
export { operationOf } from './tools/definitions.ts';
export type { ToolOperation } from './tools/definitions.ts';
export { TOOL_CALLING_INSTRUCTIONS } from './policy.ts';
